### ISSUE TITLE
这个数据为啥这么标注呢

### ISSUE THREAD

**Issue by cqray1990** [chineseocr/table-detect#26]
边界的线也没有标，横线和竖线标的并不是只是一根直线，直接标两点直线？

**Comment by nothing4any** [comment]
不是标注矩形框，是线

**Comment by cqray1990** [comment]
,

**Comment by nothing4any** [comment]
线条检测使用unet，线条和矩形框我感觉是都一样

**Comment by zhengquanhe** [comment]
> 线条检测使用unet，线条和矩形框我感觉是都一样

所以应该怎么用labelme 标注呢 是和楼主给出的json文件一样的话 看着像是单元格

**Comment by zhengquanhe** [comment]
> ![2022-09-12 09-21-55屏幕截图](https://user-images.githubusercontent.com/32585434/189558626-444323b5-57fd-4326-b09b-ec882239d8c2.png) 边界的线也没有标，横线和竖线标的并不是只是一根直线，一个矩形，这任务不对阿

后来是怎么标注的呢 我想自己标注一下数据集来训练

**Comment by nothing4any** [comment]
线标注

**Comment by Barry1915** [comment]
> > ![2022-09-12 09-21-55屏幕截图](https://user-images.githubusercontent.com/32585434/189558626-444323b5-57fd-4326-b09b-ec882239d8c2.png) 边界的线也没有标，横线和竖线标的并不是只是一根直线，一个矩形，这任务不对阿
> 
> 后来是怎么标注的呢 我想自己标注一下数据集来训练

在Edit里面选择create line

**Comment by cqray1990** [comment]
> > > ![2022-09-12 09-21-55屏幕截图](https://user-images.githubusercontent.com/32585434/189558626-444323b5-57fd-4326-b09b-ec882239d8c2.png) 边界的线也没有标，横线和竖线标的并不是只是一根直线，一个矩形，这任务不对阿
> > 
> > 
> > 后来是怎么标注的呢 我想自己标注一下数据集来训练
> 
> 在Edit里面选择create line

  提供的数据我感觉都是错的，边界的线都没有标注，有误导性

**Comment by nothing4any** [comment]
> > > > ![2022-09-12 09-21-55屏幕截图](https://user-images.githubusercontent.com/32585434/189558626-444323b5-57fd-4326-b09b-ec882239d8c2.png) 边界的线也没有标，横线和竖线标的并不是只是一根直线，一个矩形，这任务不对阿
> > > 
> > > 
> > > 后来是怎么标注的呢 我想自己标注一下数据集来训练
> > 
> > 
> > 在Edit里面选择create line
> 
> 提供的数据我感觉都是错的，边界的线都没有标注，有误导性
这个模型本质是一个分割任务，他的原理是分割线条，其实你们怎么标注只要把线标好就行，作者只是提供了一些人家自己的标注文件罢了
